---
- hosts: localhost
  connection: local

  pre_tasks:
  - name: Update packages
    apt:
      name: "*"
      state: latest
      update_cache: yes

  roles:
    - cli_tools
    - docker
    - vagrant
    - steam
    - keepassxc
    - vivaldi
