---
- name: Install aptitude using apt
  apt:
    name: aptitude
    state: present
    update_cache: true
    force_apt_get: yes

- name: Install required system packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ dependencies }}"

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update apt and install Docker
  apt:
    update_cache: true
    name: "{{ item }}"
    state: present
  loop: "{{ docker_packages }}"

- name: Install Docker Module for Python
  pip:
    name: docker
    executable: pip3

- name: Install Docker-Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.24.1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755

- name: Create Docker group
  group:
    name: docker
    state: present

- name: Get current username
  become: false
  shell: whoami
  register: current_username

- name: Add user current user to the Docker group
  user:
    name: "{{ current_username.stdout }}"
    group: "{{ current_username.stdout }}"
    groups: docker
    append: true
