---
- name: Add repository to APT
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop:
    - "deb http://archive.ubuntu.com/ubuntu/ bionic multiverse"
    - "deb http://archive.ubuntu.com/ubuntu/ bionic-updates multiverse"
    - "deb http://security.ubuntu.com/ubuntu/ bionic-security multiverse"

- name: Install Steam
  apt:
    name: steam
    state: present
    update_cache: yes
