---
dependencies:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - python3
  - python3-pip
  - virtualenv
  - python3-setuptools

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io


