---
cli_tools:
  - shellcheck
  - ncdu
  - mc
  - htop
  - traceroute
  - vim
  - tmux
  - ffmpeg
  - git
  - python3
  - python3-pip
  - curl
  - neofetch
  - jq
  - dnsutils
  - net-tools
  - whois
  - ripgrep
  - tig
  - vlc
  - moc
  - xclip
  - units
  - sct
  - i3lock-fancy
  - feh
  - speedtest-cli
  - newsboat
  - urlview

packages:
  - python3-venv
  - python-cairo
  - libcairo2-dev
  - gnome-system-monitor
  - gnome-calculator
  - gnome-software
  - gnome-logs
  - gnome-characters
  - gnome-sushi
  - rhythmbox
  - gstreamer1.0-plugins-ugly
  - gstreamer1.0-libav
  - thunderbird
  - usb-creator-gtk
  - libjack-jackd2-dev
  - libasound2-dev
  - dconf-editor
  - awesome
  - papirus-icon-theme

pip3_packages:
  - pycodestyle
  - flake8
  - pylint
  - ansible-lint
  - psutil
  - yamllint
