---
packages:
  - shellcheck
  - ncdu
  - mc
  - htop
  - traceroute
  - vim
  - tmux
  - ffmpeg 
  - git
  - python3
  - python3-pip
  - python-cairo
  - curl
  - gnome-system-monitor
  - gnome-software
  - gnome-calculator
  - gnome-logs
  - gnome-characters

pip3_packages:
  - pycodestyle
  - ansible-lint
