---
cli_tools:
  - shellcheck
  - ncdu
  - mc
  - htop
  - traceroute
  - vim
  - tmux
  - ffmpeg
  - git
  - python3
  - python3-pip
  - curl
  - neofetch
  - jq
  - dnsutils
  - net-tools
  - whois

packages:
  - python3-venv
  - python-cairo
  - libcairo2-dev
  - gnome-system-monitor
  - gnome-calculator
  - gnome-software
  - gnome-logs
  - gnome-characters
  - gnome-sushi
  - rhythmbox
  - gstreamer1.0-plugins-ugly
  - gstreamer1.0-libav
  - thunderbird
  - usb-creator-gtk

pip3_packages:
  - pycodestyle
  - ansible-lint
  - psutil
  - yamllint
