---
- name: Remove Snapd
  apt:
    name: snapd
    state: absent
    purge: yes

- name: Installing a collection of CLI tools
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ cli_tools }}"

- name: Installing a collection of packages and programs
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ packages }}"
  
- name: Install pip3 packages
  pip:
    name: "{{ item }}"
    executable: pip3
  loop: "{{ pip3_packages }}"
