---
- name: Add apt key
  apt_key:
    url: "{{ vivaldi_apt_key_url }}"
    state: present

- name: Add Vivaldi repo
  apt_repository:
    repo: "{{ vivaldi_apt_repo }}"
    state: present

- name: Install Vivaldi stable
  apt:
    name: vivaldi-stable
    state: present
    update_cache: true
